services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    networks:
      - nats-network

  live_top:
    build: ./liveTop
    depends_on:
      - nats
    environment:
      - REQUEST_LIMIT=100
      - NATS_URL=nats://nats:4222
      - EXPIRATION_SECONDS=300
      - LOOP_INTERVAL_SECONDS=1
      - VERBOSE=FALSE
    networks:
      - nats-network
    restart: unless-stopped

  broker:
    build: ./broker
    depends_on:
      - live_top
      - nats
    networks:
      - nats-network
    restart: unless-stopped

networks:
  nats-network:
    driver: bridge
